import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import Provider from "@/components/provider";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  weight: "variable",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spaceGrotesk.variable} antialiased min-h-screen font-sans bg-background text-foreground`}
      >
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
