services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: builder
    ports:
      - "8000:8000"
    environment:
      - ROBOFLOW_API_KEY=${ROBOFLOW_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEBUG=true
      - PYTHONPATH=/app
    volumes:
      - ./backend:/app
      - backend_venv:/app/.venv
      - backend_cache:/root/.cache
    working_dir: /app
    command: /app/.venv/bin/fastapi dev
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - __pycache__/
            - .venv/
        - action: rebuild
          path: ./backend/pyproject.toml

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: deps
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api/v1
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
      - frontend_next:/app/.next
    working_dir: /app
    command: pnpm dev --turbopack
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:3000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/
            - .next/
        - action: rebuild
          path: ./frontend/package.json

volumes:
  backend_venv:
    driver: local
  backend_cache:
    driver: local
  frontend_node_modules:
    driver: local
  frontend_next:
    driver: local
